controller/eks-cluster-config-handler.go
**Problem:**
When adding a nodegroup to an imported clusters an error is returned explaining that subnets are required. This is because if nodegroups do not have subnets set in spec they will use the same subnets as the cluster but networking fields in status for the cluster were not being properly set on import.
**Solution:**
Set networking fields in status on import.
**Issue:**
https://github.com/rancher/rancher/issues/28211
=> Set network fields in status on imported clusters

controller/eks-cluster-config-handler.go
**Problem:**
If multiple changes are made to the EKS cluster, it will get stuck in updating phase and not go to active when the upstream cluster goes to active.
This is because it was assumed an object would be reenqueued when updating its phase to "updating". If a cluster was already in "updating" it would not be reenqueued because it was a noop. The reenqueue is necessary for the onChange function to begin waiting on the EKS cluster and nodegroups to finish updating.
**Solution:**
If the object is already in the "updating" phase, it will be reenqueued with the reenqueue function.
**Issue:**
https://github.com/rancher/rancher/issues/28149
=> Reenqueue if already updating

controller/eks-cluster-config-handler.go, go.mod
**Problem:**
Users need the option to upgrade nodegroup kubernetes versions the amazon way or to create new nodegroups and delete ones that are outdated.
**Solution:**
Nodegroup versions must now be maintained. Control plane cannot upgraded until all nodegroup versions match. New nodegroups' versions must match the control plane's version. Nodegroup versions can at most be 1 minor version less than the control plane's version.
**Issue:**
https://github.com/rancher/rancher/issues/27777
=> Add validation to create and update

templates/template.go
**Problem:**
Need networking tags for load balancer and elb compatibility in EKS.
**Solution:**
Add following tag:
kubernetes.io/role/elb: 1
**Notes:**
"kubernetes.io/cluster" tag is added by EKS. "kubernetes.io/role/internal-elb" does not apply because only public subnets are created for the user.
**Issue:**
https://github.com/rancher/rancher/issues/28332
=> Add tag to subnets for elb compatibility

controller/eks-cluster-config-handler.go
**Problem:**
Prior, importing clusters with nodegroups that don't have instance
types on their state would cause a nil. Nodegroups will not have
instance types if they are using a launch template. This is because
the instance types are instead described on the launch template.
**Solution:**
Now, the instance type will only be copied if it exists on the
nodegroup state.
**Issue:**
https://github.com/rancher/rancher/issues/28801
=> Check length of instance types

controller/eks-cluster-config-handler.go
**Problem:**
Ssh key is showing nil instead of proper value on spec. This is because the ssh key is not being included when building the upstream spec and then the upstream spec is being used to overwrite spec.
**Solution:**
Add ssh key when building upstream state.
**Issue:**
https://github.com/rancher/rancher/issues/28937
=> Add ssh key to upstream state

controller/eks-cluster-config-handler.go
**Problem:**
Nodegroup version should be provided on create because it is required in EKS.
**Solution:**
Add validation that returns an error if a nodegroup's version is nil on create.
**Issue:**
https://github.com/rancher/rancher/issues/27777
=> Require non-nil version for nodegroups

controller/eks-cluster-config-handler.go
**Problem:**
Prior, if a cluster was in deleting the refresh handler would overwrite spec with the cluster as though it were active. The eks-operator would wait for the cluster to finish updating and then it would recreate the cluster.
Also, tag updates were not being sent because they were only being checked for updates if tags was set to nil.
**Solution:**
Do not record cluster that are in deleting. Correctly check if the tags are not nil.
**Issue:**
https://github.com/rancher/rancher/issues/28967
https://github.com/rancher/rancher/issues/28951
=> Do not record cluster that are in deleting

controller/eks-cluster-config-handler.go
There was an omission that didn't include GPU instances if a user selected it in the UI.
Issue:
https://github.com/rancher/rancher/issues/29949
=> Use GPU instance type when selected

controller/eks-cluster-config-handler.go
If the user did not select GPU images, then, during updating the upstream spec, the gpu field would be set to `nil`. This is incorrect because `nil` fields mean that field is not managed by Rancher, which is wrong in this case.
Issue:
https://github.com/rancher/rancher/issues/29949
=> Fix gpu field going to `nil`

controller/eks-cluster-config-handler.go, templates/template.go
If a user did not specify a VPC, then the operator creates one. The
created VPC was also being created with a security group. However, when
the cluster is created, a security group is added automatically.
Therefore, the security group created with the VPC is extraneous.
Issue:
https://github.com/rancher/rancher/issues/29826
=> Remove creation of extra security group

controller/eks-cluster-config-handler.go
We don't want to check for name collisions for imported clusters because the imported cluster obviously already exists in EKS.
Issue:
https://github.com/rancher/rancher/issues/29103
=> Stop checking name collisions on imported clusters

crds/eksclusterconfig.yaml, pkg/apis/eks.cattle.io/v1/types.go, pkg/codegen/main.go
Add a helm annotation to the the generated CRD. Also, add `nodegoupName` as a required field on the `NodeGroup` type.
Issue:
https://github.com/rancher/rancher/issues/30997
=> Add helm annotation and required nodegroup field

controller/nodegroup.go
ImageId was (correctly) passed as an empty string instead of null, so
eks-operator was not looking to see if a GPU instance was requested.
Issue:
https://github.com/rancher/rancher/issues/31147
=> Correctly identify when GPU instance should be used

controller/eks-cluster-config-handler.go, controller/nodegroup.go
If there is an error creating or updating a node group with a
managed launch template, then there could be many versions of the
launch template created. The operator should clean them up so there are
not a bunch leftover for no reason.
Issue:
https://github.com/rancher/rancher/issues/31263
=> Delete launch template versions on error

controller/nodegroup.go
The user data should be fully base64 encoded when creating the initial
launch template. The decoding is handled differently for different AWS
regions. This was tested to work with multiple regions.
Issue:
https://github.com/rancher/rancher/issues/31612
=> Encode fake userdata when creating launch template

scripts/package-helm
The chart version sed command was inadvertently overwriting the
rancher-version annotation. This change fixes that issue.
Issue:
https://github.com/rancher/rancher/issues/32293
=> Fix version sed for chart version

pkg/apis/eks.cattle.io/v1/types.go
Opt into new "pointer" field attribute from norman that will convert any
type to a pointer in the generated client code. The generated client code
includes "omitempty" JSON tags, which means that for maps and slices,
unset and empty values are both sent to the server as unset, which
breaks the cluster create validation. With this change, there's now a
difference between a nil value and an empty allocated map or slice in the
client code. Strings can now also use this attribute.
https://github.com/rancher/rancher/issues/32440
https://github.com/rancher/rancher/issues/32553
=> Use norman:"pointer" for nullable fields

package/Dockerfile
Running the container as a non-root user allows it run on hardened clusters.
Issue:
https://github.com/rancher/rancher/issues/33172
Original PR:
https://github.com/rancher/eks-operator/pull/42
=> [backport] Add USER directive to image for hardened clusters

controller/eks-cluster-config-handler.go, controller/nodegroup.go, controller/nodegroup_test.go, go.mod, scripts/ci, scripts/test, utils/map.go
**Problem:**
Prior, if only a label update was necessary, the scaling config
fields were not included in the nodegroup config update. This
is considered invalid and will cause an error to be returned.
**Solution:**
Now, scaling config fields are included whether they need to be
updated or not. An additional bug has been fixed where if some
labels needed to be deleted and other updated, only the updated
labels would be added to the config update.
**Issue:**
https://github.com/rancher/rancher/issues/33302
=> Fix label updates

charts/eks-operator/templates/deployment.yaml, package/Dockerfile, package/entrypoint.sh
The SLE image requires that c_rehash is run before additional trusted CAs
will be detected. Therefore, an entrypoint script is added to accomplish
this.
In addition, fsGroup is added so that c_rehash (which is run as the
eks-operator user) can read the cert that is mounted.
Issue:
https://github.com/rancher/rancher/issues/31846
=> Run c_rehash before launching the operator

.gitignore, package/Dockerfile, package/entrypoint.sh
This is a backport of a change in 2.6. Using the SLES image, combined
with USER changes, allow additional certificates to be passed to the
container for situations when Rancher is run behind a proxy.
Issue:
https://github.com/rancher/rancher/issues/32903
=> Use SLES base image

charts/eks-operator/templates/_helpers.tpl, charts/eks-operator/values.yaml
Rancher sets the default registry under
`global.cattle.systemDefaultRegistry`. Without this change, the chart
wasn't picking up the setting and would still try to pull images from
dockerhub. This change aligns the setting with the way Rancher expects
to use it and with the way other charts expose it.
https://github.com/rancher/rancher/issues/35485
=> Fix system default registry setting

charts/eks-operator/Chart.yaml
The annotations were also rearranged to be in alphabetical order.
Issue:
https://github.com/rancher/rancher/issues/35100
=> Add kube-version annotation to chart

pkg/apis/eks.cattle.io/v1/types.go
Address https://github.com/rancher/rancher/issues/36128.
A KEv2 cluster imported with the rancher2 terraform provider will currently delete all node groups on import if no node groups are specified in the terraform config. 
This is happening because the `NodeGroups` cluster config field (and all slices and maps) in the KEv2 operators have the `norman:pointer` tag. The problem is that the `norman:pointer` tag is added to fields that are already pointers. When node groups is not specified in the terraform config, terraform sets the node group field in the management cluster yaml as an empty array instead of null. If node groups is an empty array, Rancher deletes all node groups from the imported cluster because that is the template given: no node groups. Removing the incorrect tag will make …
=> Remove norman:pointer tags from EKS operator

controller/nodegroup.go
Issue: https://github.com/rancher/rancher/issues/38014
This PR https://github.com/rancher/eks-operator/pull/60 is being reverted after a design discussion whose conclusion was this: _we want how rancher handles security groups in EKS to have parity with vanilla EKS_. EKS will only add the default security group to node instances _unless_ there are security group(s) on the launch template, in which case those security group(s) replace the default on the nodes. Rancher will not add custom security groups to the launch template; any security groups defined by the user in the rancher UI will only be added at cluster level.
=> Revert add rancher security groups to launch template

go.mod, go.sum
Issue:
https://github.com/rancher/rancher/issues/38698
https://github.com/rancher/dashboard/issues/6731
Update AWS SDK to [version v1.44.83](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.83) to pull in latest changes and be able to set minimum node scaling to 0. @kinarashah if this needs to be 1.44.8 please correct me.
Dev smoke test
- Deploy 2 node EKS cluster - PASS
- Deploy a 2 node EKS cluster with a node group with minsize=0 - PASS
- Deploy an EKS cluster with a node group (desired=1, max=1, min=0) - PASS
- Deploy an EKS with 2 node groups with 1 node in each. Scale one node group down to 0 in EKS, confirm the cluster stays active in rancher. Scale it back up to 1, confirm no disconnect in rancher - PASS
=> Update AWS SDK to latest version 1.44

charts/eks-operator/templates/deployment.yaml, charts/eks-operator/values.yaml
Related to https://github.com/rancher/rancher/issues/37927
The purpose of this PR is to add the ability to set a priorityClassName for pods installed by Rancher.
=> Adds priorityClassName to deployments.

pkg/generated/controllers/core/factory.go, pkg/generated/controllers/eks.cattle.io/factory.go
Run make generate to fix CI failures, `make verify` fails because of outdated controllers.
=> Run make generate

controller/eks-cluster-config-handler.go, pkg/eks/create.go, pkg/eks/create_test.go, test/e2e/templates/basic-cluster.yaml
Allow nil node role in cluster spec will result in a node role being generated by the controller https://github.com/rancher/eks-operator/blob/master/controller/nodegroup.go#L261. Currently `""` is the only allowed option for generating a new node role but from our code logic point of view it shouldn't matter because we already treat empty strings and nil values the same.
I also made this field nil in our e2e so we can capture this case too.
https://github.com/rancher/rancher/issues/41123
=> Allow nil node role in cluster spec

.golangci.yml, controller/eks-cluster-config-handler.go, controller/nodegroup_test.go, pkg/codegen/main.go, test/e2e/config/config.go
This PR:
- Enables more linters in the .golangci.yaml to have a better aligned package import aliases
- Fixes all lint errors as a consequence of newly added linters
=> 🌱 Enable more linters

controller/eks-cluster-config-handler.go, controller/errors.go, controller/external.go
Some functions are used in rancher/rancher so they have to be public. We added API diff workflow to make sure that it won't happen again.
=> Bring back functions that are used in rancher

README.md
- When releasing unRC'ed version of the operator, the version should stay the same and not bump to a new minor version
- some minor improvement on notes related to tagging (with signature and annotation)
=> 📖  Clarify a bit more tagging a release in root README.md

controller/eks-cluster-config-handler.go, pkg/eks/create.go, pkg/eks/create_test.go, pkg/eks/get.go, pkg/eks/get_test.go, pkg/eks/update.go, pkg/eks/update_test.go
This PR fixes couple of issues:
- Remove AWS clients from the handler structure, currently, we reassign clients on each reconciliation. It hasn't been an issue but is not an ideal solution.
- Initialize AWS clients also in `OnEksConfigRemoved`
- Make arguments for AWS service calls pointers because they sometimes have to modify input objects.
=> Fix AWS clients initialization

.github/scripts/update-rancher-charts.sh
If we're adding a new version to [release.yaml](https://github.com/rancher/charts/blob/dev-v2.7/release.yaml) there 2 things the script can do:
- If eks-operator record is present in the list, it should add new version to the list, currently `sed` instruction for it is broken because it doesn't add proper indentation.
- If eks-operator record is not present, the script creates it. In the current implementation, `if grep -qv "rancher-eks-operator:" release.yaml; then` doesn't work as expected so I replaced it with a new command.
Result of the test run: https://github.com/rancher/charts/pull/2706
=> Fix chart update workflow

.golangci.yml, charts/eks-operator-crd/templates/crds.yaml, controller/eks-cluster-config-handler.go, pkg/apis/eks.cattle.io/v1/types.go, pkg/apis/eks.cattle.io/v1/zz_generated_deepcopy.go, pkg/eks/create.go, pkg/eks/create_test.go, pkg/eks/get.go, pkg/eks/get_test.go, pkg/eks/services/eks.go, pkg/eks/services/iam.go, pkg/eks/services/mock_services/eks_mock.go, pkg/eks/services/mock_services/iam_mock.go, templates/template.go
Issue #106 
With EKS v1.23 and higher it requires the use of the out of tree EBS CSI driver. If this isn't available then and PVC will not be bound and pods using the volumes will stay in pending.
This is a problem for creating new clusters and for upgrading clusters from 1.22
The solution is based on the support utility rancherlabs/support-tools#217 which has been used as a workaround while the functionality is added to the operator.
- A boolean field is added to `EKSClusterConfigSpec` [EBSCSIDriver](https://github.com/salasberryfin/eks-operator/blob/46750b97cb4bb45019825cb2a90536bceca46854/pkg/apis/eks.cattle.io/v1/types.go#L46). This will require to update the EKS create cluster UI to have an option to set this new spec. 
- If set to true, the EBS CSI driver for EKS will be installed …
=> Out of tree EBS CSI Driver

.github/workflows/nightly-publish.yaml
Added a GHA workflow that will build and publish the operator every night to ttl.sh. This is to aid testing the HEAD.
Relates: #192
=> chore: added nightly build & publish

pkg/eks/create.go, pkg/eks/create_test.go, utils/map.go
This change includes a fix to ensure that the instance resource tags are properly propogated to resources via the launch template.
Issue: #205
=> fix: tag instances resources

controller/eks-cluster-config-handler.go
This bug was initially reported by @cpinjani while validating launch template behavior in the Rancher Dashboard https://github.com/rancher/dashboard/issues/9606
With `eks-operator:v1.2.1` the list of versions of Rancher-managed launch templates was not properly populated in the cluster's yaml `eksStatus`, which made the launch template information unavailable in the UI.
=> [v2.8] fix: cluster config not showing launch template versions 

controller/eks-cluster-config-handler.go
This bug was initially reported by @cpinjani while validating launch template behavior in the Rancher Dashboard https://github.com/rancher/dashboard/issues/9606
With `eks-operator:v1.2.1` the list of versions of Rancher-managed launch templates was not properly populated in the cluster's yaml `eksStatus`, which made the launch template information unavailable in the UI.
=> [v2.7] fix: cluster config not showing launch template versions

controller/eks-cluster-config-handler.go
This bug was initially reported by @cpinjani while validating launch template behavior in the Rancher Dashboard https://github.com/rancher/dashboard/issues/9606
With `eks-operator:v1.2.1` the list of versions of Rancher-managed launch templates was not properly populated in the cluster's yaml `eksStatus`, which made the launch template information unavailable in the UI.
=> fix: cluster config not showing launch template versions

controller/eks-cluster-config-handler.go
This panic is caused by a node group created from the AWS Console using a malformed launch template. This was specifically detected while trying to use the default version of the Rancher-managed launch template, which only contains a placeholder string in the user data.
=> [v2.7] fix: rancher panics when node group fails

controller/eks-cluster-config-handler.go
This panic is caused by a node group created from the AWS Console using a malformed launch template. This was specifically detected while trying to use the default version of the Rancher-managed launch template, which only contains a placeholder string in the user data.
=> [v2.8] fix: rancher panics when node group fails

controller/eks-cluster-config-handler.go
This panic is caused by a node group created from the AWS Console using a malformed launch template. This was specifically detected while trying to use the default version of the Rancher-managed launch template, which only contains a placeholder string in the user data.
=> fix: rancher panics when node group fails

.github/dependabot.yaml
This PR:
* Allows patch updates on dependabot ignore list
* Add dependencys group for dependabot
=> 🌱 Group k8s.io dependency updates and add aws-sdk-go to ignore list

pkg/apis/eks.cattle.io/v1/types.go
Issue: https://github.com/rancher/eks-operator/issues/203
=> Document EKSClusterConfig API

.github/dependabot.yaml
**What this PR does / why we need it:**
We have to check outdated dependency also for `release-v2.8` and `release-v2.7` branches
=> Improve dependabot to track other branches

.github/workflows/nightly-publish.yaml
Use the reusable workflow for the nightly publish as we're already doing in other hosted providers. 
Issue #
**Checklist**:
=> chore: use reusable workflow for nightly publish

scripts/setup-kind-cluster.sh, test/e2e/basic_cluster_test.go, test/e2e/templates/basic-cluster.yaml
Update E2E tests following existing test cases in other hosted providers.
This PR also updates Kubernetes version to v1.26 as end of standard support for v1.25 in EKS is approaching.
Issue #97 
**Checklist**:
=> chore: add new e2e test cases

.github/dependabot.yaml
Dependabot is creating PRs for `wrangler` updates after the move to `github.com/rancher/wrangler/v2`, which is not covered in the existing ignore rule. This change also removes patch updates from being tracked.
Issue #
**Checklist**:
=> chore: add ignore rule for dependabot updates on wrangler v2

test/e2e/basic_cluster_test.go, test/e2e/templates/basic-cluster.yaml
Update E2E tests following existing test cases in other hosted providers.
This PR also updates Kubernetes version to v1.26 as end of standard support for v1.25 in EKS is approaching.
Issue #97 
**Checklist**:
=> test: add node group test to e2e

charts/eks-operator-crd/templates/crds.yaml, controller/eks-cluster-config-handler.go, pkg/apis/eks.cattle.io/v1/types.go, pkg/apis/eks.cattle.io/v1/zz_generated_deepcopy.go, pkg/eks/create.go, pkg/eks/create_test.go, test/e2e/basic_cluster_test.go, test/e2e/config/config.yaml, test/e2e/templates/basic-cluster.yaml
Adds support for ARM node groups. The new API field `Arm` was introduced in the NG properties and disabled by default,  and when it is set to `true` with the appropriate **instanceType** (i.e a1.large instead of t3.medium) for ARM, a node group will be created based off of the ARM AMI types. 
Issue #292 
To be able to use this feature:
1. A new operator release needs to be cut
2. A new release of the operator bumped in Rancher with a new field added in https://github.com/rancher/rancher/tree/release/v2.9/pkg/controllers/management/eks/test files
3. daily e2e tests might fail until then both of the above are completed
I have tested it by:
1. Releasing a new operator version from my …
=> 🌱 Add Arm support for EKS NodeGroup

go.mod
It has to be reverted because it is breaking Rancher v2.9 integration, Rancher v2.9 still uses version `github.com/rancher/rancher/pkg/apis` which we have to revert.
Issue #
**Checklist**:
=> [v2.9] Revert github.com/rancher/rancher/pkg/apis version

Dockerfile.dapper, package/Dockerfile
Issue: https://github.com/rancher/eks-operator/issues/407 (cherry picked from commit 483d6c8270c08f4f293b15f02026e1381ac20201)
Issue #
**Checklist**:
=> [v2.8] security: bump operator base image to bci-micro:15.5

Dockerfile.dapper, package/Dockerfile
Issue: https://github.com/rancher/eks-operator/issues/407 (cherry picked from commit 483d6c8270c08f4f293b15f02026e1381ac20201)
Issue #
**Checklist**:
=> [v2.7] security: bump operator base image to bci-micro:15.5

controller/external.go
Issue: https://github.com/rancher/eks-operator/issues/336
Issue #
**Checklist**:
=> Add StartEC2Service and StartEKSService to external functions

controller/eks-cluster-config-handler.go, controller/external.go, controller/internal.go
We would like to avoid using secretsCache, because cache might be outdated. Secrets are considered sensitive and we might want to always see the latest changes.
Issue: https://github.com/rancher/aks-operator/issues/159 (cherry picked from commit d83f728836d53788c4af23abe80fd473d4767f2c)
Issue #
**Checklist**:
=> [v2.9] Avoid using secretsCache for secrets

go.mod, go.sum
Issue # https://github.com/rancher/eks-operator/security/dependabot/28
**Checklist**:
=> [v2.8] fix: Bump `github.com/rancher/norman` version to address CVE-2023-32193

controller/eks-cluster-config-handler.go, controller/eks-cluster-config-handler_test.go
Added a validation check to prevent duplicated node group names during an update. I've also updated the relevant error string returned during creation to match EKS terminology (node groups) and Go style guidelines (lowercase).
Issue #221 
**Checklist**:
=> [v2.8] Prevent duplicated node group names

.github/dependabot.yaml
Dependabot is ignoring updates for k8s dependencies but only for major and minor versions. As k8s is updated manually in sync with Rancher core, we also need to ignore patch releases.
Issue #
**Checklist**:
=> chore: make dependabot ignore all k8s updates

.github/workflows/apidiff.yaml, .github/workflows/e2e-branch.yaml, .github/workflows/lint.yaml, .github/workflows/update-rancher-charts.yaml, .github/workflows/update-rancher-dep.yaml, Makefile
Replace unapproved GH Actions with approved ones. To [enhance security](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), the 3rd-party GH Action used to install kind is pinned to a commit SHA. Note that dependabot will [update](https://github.com/dependabot/dependabot-core/issues/4691) both the commit SHA and the human-readable value next to it.
Issue https://github.com/rancher/highlander/issues/89
**Checklist**:
=> fix: Replace unapproved GH Actions with approved ones

Dockerfile.dapper, Makefile
=> Disable C calls from GO in operator

.github/workflows/apidiff.yaml, .github/workflows/build.yaml, .github/workflows/e2e.yaml, .github/workflows/lint.yaml, .github/workflows/unit.yaml, .github/workflows/update-rancher-charts.yaml, .github/workflows/update-rancher-dep.yaml, .github/workflows/verify.yaml, Makefile
Replace unapproved GH Actions with approved ones. To [enhance security](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), the 3rd-party GH Action used to install kind is pinned to a commit SHA. Note that dependabot will [update](https://github.com/dependabot/dependabot-core/issues/4691) both the commit SHA and the human-readable value next to it.
Issue https://github.com/rancher/highlander/issues/89
- actions/checkout has been updated to v4 to eliminate Node runtime version warnings
- actions/setup-go has been updated to v5 to eliminate Node runtime version warnings
- Upon checkout, credentials are not being …
=> [v2.9] fix: Replace unapproved GH Actions with approved ones

.github/workflows/apidiff.yaml, .github/workflows/build.yaml, .github/workflows/e2e.yaml, .github/workflows/lint.yaml, .github/workflows/nightly-publish.yaml, .github/workflows/scan.yaml, .github/workflows/unit.yaml, .github/workflows/update-rancher-charts.yaml, .github/workflows/update-rancher-dep.yaml, .github/workflows/verify.yaml, Makefile
Replace unapproved GH Actions with approved ones. To [enhance security](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), the 3rd-party GH Action used to install kind is pinned to a commit SHA. Note that dependabot will [update](https://github.com/dependabot/dependabot-core/issues/4691) both the commit SHA and the human-readable value next to it.
Issue https://github.com/rancher/highlander/issues/89
- actions/checkout has been updated to v4 to eliminate Node runtime version warnings
- actions/setup-go has been updated to v5 to eliminate Node runtime version warnings
- Upon checkout, credentials are not being …
=> [v2.8] fix: Replace unapproved GH Actions with approved ones

.github/workflows/apidiff.yaml, .github/workflows/build.yaml, .github/workflows/e2e.yaml, .github/workflows/lint.yaml, .github/workflows/nightly-publish.yaml, .github/workflows/scan.yaml, .github/workflows/unit.yaml, .github/workflows/update-rancher-charts.yaml, .github/workflows/update-rancher-dep.yaml, .github/workflows/verify.yaml, .trivyignore, Makefile, test/e2e/Dockerfile.e2e
Replace unapproved GH Actions with approved ones. To [enhance security](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), the 3rd-party GH Action used to install kind is pinned to a commit SHA. Note that dependabot will [update](https://github.com/dependabot/dependabot-core/issues/4691) both the commit SHA and the human-readable value next to it.
Issue https://github.com/rancher/highlander/issues/89
- actions/checkout has been updated to v4 to eliminate Node runtime version warnings
- actions/setup-go has been updated to v5 to eliminate Node runtime version warnings
- Upon checkout, credentials are not being …
=> [v2.7] fix: Replace unapproved GH Actions with approved ones

controller/external.go, pkg/eks/create.go, pkg/eks/create_test.go
Amazon Linux 2 end of support date is 2025-06-30,
This change is updating AMI to Amazon Linux 2023.
Issue: https://github.com/rancher/eks-operator/issues/568 (cherry picked from commit fb28a54c64a44290b3b2f6650c9948eabc3b4bda)
Issue #
**Checklist**:
=> [v2.9] Change default AMI type to Amazon Linux 2023

controller/external.go, pkg/eks/create.go, pkg/eks/create_test.go
Amazon Linux 2 end of support date is 2025-06-30,
This change is updating AMI to Amazon Linux 2023.
Issue: https://github.com/rancher/eks-operator/issues/568
Issue #
**Checklist**:
=> Change default AMI type to Amazon Linux 2023

pkg/eks/update.go, pkg/eks/update_test.go
Update getLoggingTypesUpdate function when there are no changes for logging types. Adding also test scenario to avoid regressions in the future.
Issue: https://github.com/rancher/eks-operator/issues/546
Issue #
**Checklist**:
=> Fix logging types updates

.github/workflows/e2e-workflow.yaml, test/e2e/templates/basic-cluster.yaml
Removed e2e tests for 2.7. Also bumped the version of k8s used in the e2e test to 1.28.
**Checklist**:
=> ci: Remove e2e tests for 2.7

test/e2e/config/config.yaml, test/e2e/suite_test.go
This PR updates the e2e tests for `release-v2.9` to use the latest development Rancher Helm chart (currently `2.9.0-rc1`) and overrides the image tag with `v2.9-head`.
**Checklist**:
=> [v2.9] fix: Use version v2.9-head of Rancher for e2e tests

.github/workflows/build.yaml, .github/workflows/lint.yaml, .github/workflows/scan.yaml, .github/workflows/unit.yaml, .github/workflows/verify.yaml, test/e2e/config/config.yaml, test/e2e/suite_test.go
This PR updates the e2e tests for `release-v2.8` to use the latest Rancher Helm chart (currently `2.8.5`) and overrides the image tag with `v2.8-head`. It also updates the CI workflows to run against `release-v2.8` upon push.
**Checklist**:
=> [v2.8] fix: Use version v2.8-head of Rancher for e2e tests

.drone.yml, .github/workflows/release.yaml, .goreleaser.yaml, .trivyignore
Up until recently, creating a new GitHub release (and associated artifacts) when a new tag was created, was being done using Drone CI. Now that Drone CI has been deprecated, there is a GitHub Actions workflow that is responsible for doing this. In fact, most of the work is delegated to goreleaser which is being invoked as part of that workflow.
Cherry pick of the commits of https://github.com/rancher/eks-operator/pull/655
Issue #654 
**Checklist**:
=> [v2.7] ci: Add goreleaser config and update release workflow

.github/workflows/release.yaml
Specify the exact tag for the new release. This is necessary because by default, goreleaser sorts tags by name before selecting which tag to release, which causes problems when >1 tags point to the same commit (un-rc process). From https://goreleaser.com/cookbooks/set-a-custom-git-tag/
Issue #704 
**Checklist**:
=> [v2.8] ci: Specify the exact tag for the new release

.github/workflows/release.yaml
Specify the exact tag for the new release. This is necessary because by default, goreleaser sorts tags by name before selecting which tag to release, which causes problems when >1 tags point to the same commit (un-rc process). From https://goreleaser.com/cookbooks/set-a-custom-git-tag/
Issue #704 
**Checklist**:
=>  ci: Specify the exact tag for the new release

pkg/eks/update.go, pkg/eks/update_test.go
Disable all logging types when option loggingTypes is empty. Adding also test coverage to avoid regressions.
Issue: https://github.com/rancher/eks-operator/issues/673
Issue #
**Checklist**:
=> Disable all logging types when empty

pkg/eks/update.go, pkg/eks/update_test.go
Disable all logging types when option loggingTypes is empty. Adding also test coverage to avoid regressions.
Issue: https://github.com/rancher/eks-operator/issues/673 (cherry picked from commit 8f098a44862c89619be10741c5025f425ebabb64)
Issue #
**Checklist**:
=> [v2.9] Disable all logging types when empty

controller/external.go, pkg/eks/create.go, pkg/eks/create_test.go
Issue: https://github.com/rancher/eks-operator/issues/568 (cherry picked from commit dbe9ecac09d1caf2dd6749f363877c65200b830e)
Issue #
**Checklist**:
=> [v2.9] Update default AMI types for Nvidia GPU

main.go
Add cli flag and set log level debug option. This is helpful when debugging the operator locally. The codebase has debug log statement at multiple places but does not set the log level.
=> Add debug flag for log level

main.go
Cherry-pick from #819 
Add cli flag and set log level debug option. This is helpful when debugging the operator locally. The codebase has debug log statement at multiple places but does not set the log level.
=> [v2.9] Add debug flag for log level

main.go
Cherry-pick from #819
Add cli flag and set log level debug option. This is helpful when debugging the operator locally. The codebase has debug log statement at multiple places but does not set the log level.
=> [v2.8] Add debug flag for log level

controller/external.go, pkg/eks/create.go, pkg/eks/create_test.go
This reverts commit bb73bdb6605f0485acd51bda9801ab40ce6e2538, reversing changes made to 2fffed6c5e96d8ad36154f8ad419a029fbca486f.
It looks like the new GPU AMI is still [not available](https://github.com/rancher/eks-operator/issues/568#issuecomment-2340718035).
Issue #568 
**Checklist**:
=> Revert "Merge pull request #790 from mjura/gpu-v2.9"

controller/external.go, pkg/eks/create.go, pkg/eks/create_test.go
This reverts commit 5746bbc89951a078eb21d7fb91e13692898ec805, reversing changes made to dbe9ecac09d1caf2dd6749f363877c65200b830e.
It looks like the new GPU AMI is still [not available](https://github.com/rancher/eks-operator/issues/568#issuecomment-2340718035).
**Checklist**:
=> Revert "Merge pull request #789 from mjura/gpu-main"

.trivyignore, Dockerfile.dapper, controller/eks-cluster-config-handler.go
Although the Go module version for release-v2.7 is set to 1.20, we used 1.19 to compile it. Bumping the Go version helps mitigate against vulnerabilities present in 1.19 but addressed in 1.20.
**Checklist**:
=> [v2.7] Bump Go to 1.20.14

.github/workflows/scan.yaml
(cherry picked from commit f11b2b51b0d04348fb8b7f25820abd524a02b3d6)
We frequently get CI failures when scanning with trivy because there have been too many requests to download the vulnerability db from the rancher org (because many of its repos are using it).
This PR updates the Scan workflow to include additional repositories to be used if trivy fails to retrieve the vulnerability db from the primary source.
Issue #924 
Source for fix: https://github.com/aquasecurity/trivy/discussions/7668#discussioncomment-10884984
**Checklist**:
=> [v2.9] ci: Fix trivy action timeout

controller/external.go, pkg/eks/create.go, pkg/eks/create_test.go
Bump AMI Amazon Linux 2023 with Nvidia support
(cherry picked from commit 824e7bb30f5914b8ca4d36e69df7cb6a696bcd21)
Issue #568 
There was a mistake and a previous [PR](https://github.com/rancher/eks-operator/pull/988) was targeting `main` instead of `release-v2.10`
**Checklist**:
=> [v2.10] Bump AMI Amazon Linux 2023 with Nvidia support

pkg/eks/create.go, pkg/eks/create_test.go
Issue https://github.com/rancher/eks-operator/issues/986
**Checklist**:
=> Prevent panic on no launch template ID

controller/eks-cluster-config-handler.go, controller/eks-cluster-config-handler_test.go
in case a conflict error occurs the controller's recordError Function will just print it and return the error as it is.
conflict errors occur since rancher also modifies eksconfig object. As conflict error returns empty object, errors like `"Error recording ekscc [] failure message: resource name may not be empty"` occurs when we try to add a failure message to eksconfig status and update it.
The operation which results in conflict gets applied automatically in the next reconciliation call of the controller hence it is safe to just log it. 
Issue # https://github.com/rancher/eks-operator/issues/1009
**Checklist**:
=> [main] handle conflict errors while updating eksClusterConfig

charts/eks-operator-crd/templates/crds.yaml, controller/eks-cluster-config-handler.go, controller/eks-cluster-config-handler_test.go, pkg/apis/eks.cattle.io/v1/types.go, pkg/apis/eks.cattle.io/v1/zz_generated_deepcopy.go, pkg/eks/get.go, pkg/eks/get_test.go, pkg/eks/services/eks.go, pkg/eks/services/mock_services/eks_mock.go
the cluster refresh controller in rancher reverts some updates to the eks cluster because upstream eks cluster remains in active state for a few seconds after we push an update. 
Added a check to retrieve eks cluster updates and if in case any update is in progress the controller will just return now.
Issue https://github.com/rancher/eks-operator/issues/752
**Checklist**:
=> [main] check upstream cluster updates when updating the cluster

charts/eks-operator-crd/templates/crds.yaml, controller/eks-cluster-config-handler.go, controller/eks-cluster-config-handler_test.go, pkg/apis/eks.cattle.io/v1/types.go, pkg/apis/eks.cattle.io/v1/zz_generated_deepcopy.go, pkg/eks/get.go, pkg/eks/get_test.go, pkg/eks/services/eks.go, pkg/eks/services/mock_services/eks_mock.go
backport for PR: https://github.com/rancher/eks-operator/pull/1166
Issue #
**Checklist**:
=> [release-v2.11] check upstream cluster updates in the cluster as well while updating

controller/eks-cluster-config-handler.go, pkg/eks/create.go, templates/helpers.go, templates/suite_test.go, templates/template.go, templates/templates_test.go
it fixes the templates for us-gov regions. It sets the arn based on the regions and also the dns suffix.
Issue -  https://github.com/rancher/rancher/issues/47518
**Checklist**:
=> [main] generate cloud formation templates as per aws region

controller/eks-cluster-config-handler.go, pkg/eks/create.go, templates/helpers.go, templates/suite_test.go, templates/template.go, templates/templates_test.go
backport PR for: https://github.com/rancher/eks-operator/pull/1271
Issue # https://github.com/rancher/rancher/issues/49734
**Checklist**:
=> [release-v2.10] generate cloud formation templates as per aws region

controller/eks-cluster-config-handler.go, pkg/eks/create.go, templates/helpers.go, templates/suite_test.go, templates/template.go, templates/templates_test.go
backport for https://github.com/rancher/eks-operator/pull/1271
Issue # https://github.com/rancher/rancher/issues/47518
**Checklist**:
=> [release-v2.11] generate cloud formation templates as per aws region

.github/workflows/delete-old-versions.yaml
Introduce a scheduled workflow to automatically delete outdated images and charts for the eks-operator, maintaining a specified number of versions for both the eks-operator and related charts.
=> [main] Add workflow to delete old images and charts for eks-operator

.github/workflows/release.yaml, charts/eks-operator/Chart.yaml
- Add support for auto chart bump in release GHA
- New charts will be pushed to the branch with the name chart/[MAJOR-VERSION].[MINOR-VERSION]
- Bump `rancher-version` and `kube-version`
- https://github.com/rancher/rancher/issues/49161
=> [v2.10] Add support for auto chart bump in release GHA
