- controller/eks-cluster-config-handler.go
**Problem:**
Local networking fields were only being copied from status if status was recently updated. If the object reentered the create
logic after the networking fields on status are updated, the local networking variables are left blank. This causes errors during cluster creation in EKS.
**Solution:**
Always copy networking fields from status.
**Issue:**
https://github.com/rancher/rancher/issues/28129
> Always set local networking variables

- controller/eks-cluster-config-handler.go
**Problem:**
Updating multiple fields on eks cluster may result in an error stating that cluster is already being updated.
**Solution:**
Skip recording "cluster currently updating" error.
Cluster updating error is valid in that the controller should retry but there is no actionable resolution as far as a user is concerned. An update that has either been initiated by eks-operator or another source is already in progress. It is possible an update is not being immediately reflected in upstream cluster state. The config object will reenter the controller and then the
controller will wait for the update to finish.
**Issue:**
https://github.com/rancher/rancher/issues/28408
> Skip recording "cluster currently updating" error

- controller/eks-cluster-config-handler.go
- utils/map.go
**Problem:**
Cannot update nodegroup fields: min size, max size, desired size, labels, tags.
**Solution:**
Detect changes between aforementioned fields and upstream and update fields that do not match.
**Issues:**
https://github.com/rancher/rancher/issues/28153
https://github.com/rancher/rancher/issues/28151
https://github.com/rancher/rancher/issues/28126
> Add ng update options

- controller/eks-cluster-config-handler.go
**Problem:**
It is possible that imported clusters will have no public access sources. Prior, importing these clusters would cause an out of
bounds error.
**Solution:**
Now, the sources will not be indexed if empty.
**Issue:**
https://github.com/rancher/rancher/issues/28533
https://github.com/rancher/rancher/issues/19051
> Filter public access sources before comparison 

- controller/eks-cluster-config-handler.go
**Problem:**
Update from public access to private access if not working. Public and private access updates need to be sent together. When they are sent one at a time the request may be denied due to having both public and private access disabled.
Other commits are currently under review in other PR. Cherry-picked so conflicts are easier to resolve later.
**Solution:**
Send public and private access updates together.
**Issue:**
https://github.com/rancher/rancher/issues/28115
> Access update fix

- controller/eks-cluster-config-handler.go
**Problem:**
Secrets created by eks-operator were not being cleaned up after corresponding EKSClusterConfig was deleted.
**Solution:**
Add EKSClusterConfig as owner reference
**Issue:**
https://github.com/rancher/rancher/issues/29040
> Add owner reference to secret

- crds/eksclusterconfig.yaml
- go.mod
- go.sum
- pkg/generated/controllers/core/v1/interface.go
- pkg/generated/controllers/core/v1/node.go
- pkg/generated/controllers/core/v1/pod.go
- pkg/generated/controllers/core/v1/secret.go
- pkg/generated/controllers/eks.cattle.io/v1/eksclusterconfig.go
- pkg/generated/controllers/eks.cattle.io/v1/interface.go
**Problem:**
Go generate produces a diff and wrangler needs to be updated.
**Solution:**
Ran go generate as it wasn't ran after last wrangler update.
Updated wrangler.
Ran go generate again.
**Issue:**
https://github.com/rancher/rancher/issues/29294
> Update wrangler e86b

- controller/eks-cluster-config-handler.go
Before creating a new hosted EKS cluster, we first check the existing
clusters to ensure the name provided by the user is unique. If it is not
unique, then we wait for user to delete the cluster in Rancher or the
existing cluster in EKS.
If the cluster never advanced passed the "not created" status, then we
also should not delete any existing EKS clusters.
Issue:
https://github.com/rancher/rancher/issues/29103
> Disallow creating cluster if one with same name exists

- controller/nodegroup.go
The launch template data should use the image's root device name when
setting the disk size. Otherwise, a new device is attached to the image,
which is not the intended outcome. The root device size should be set to
the size the user submits.
Issue:
https://github.com/rancher/rancher/issues/31361
> Use root device name when setting disk size

- controller/eks-cluster-config-handler.go
If a user edits a cluster at the exact right (or wrong) time, then the
UpdateStatus call may produce a conflict and will error. When the
controller re-enters the create function, it will try to verify that a
cluster with the same name in EKS does not exist. It will find the one
that was created and error.
Instead, we retry the UpdateStatus call on conflict to protect against
this happening.
Issue:
https://github.com/rancher/rancher/issues/31608
> Fix possible conflict when editing during provision

- pkg/apis/eks.cattle.io/v1/types.go
Backport of https://github.com/rancher/eks-operator/pull/38
> Use norman:"pointer" for nullable fields

- controller/eks-cluster-config-handler.go
- controller/nodegroup.go
- controller/nodegroup_test.go
- go.mod
- go.sum
- scripts/ci
- scripts/test
- utils/map.go
**Original PR:**
https://github.com/rancher/eks-operator/pull/45
> [Backport]: Fix label updates release v1.0

- charts/eks-operator-crd/Chart.yaml
- charts/eks-operator/Chart.yaml
- charts/eks-operator/templates/_helpers.tpl
- charts/eks-operator/templates/deployment.yaml
- charts/eks-operator/values.yaml
This adds new annotations for app and marketplace UI changes. It also adding the correct tolerations and selectors for running in a mixed workload cluster.
* https://github.com/rancher/rancher/issues/36401
Verified that it will deploy in a mixed workload cluster successfully after the changes.
> Changes required to support mixed workload clusters.

- charts/eks-operator/templates/deployment.yaml
Current nodeSelectors and tolerations are broken if you try supplying anything except default.
Larger PR: https://github.com/rancher/charts/pull/1813
> Fix nodeSelectors and tolerations

- controller/eks-cluster-config-handler.go
Issue: https://github.com/rancher/rancher/issues/37650 
When a call to `UpdateNodeGroupVersion` fails due to a custom AMI version causing node provisioning to fail in EKS, the failure is expected but lasso spams the EKS logs every second. This happens because the error message that is returned from EKS has metadata with a unique `requestID` in the body. Since the error message is different every time, [this code](https://github.com/rancher/eks-operator/blob/1b8dfe2ea04eee43fd362c6da0e1cef2a09cb600/controller/eks-cluster-config-handler.go#L122) is skipped and the [Status gets updated](https://github.com/rancher/eks-operator/blob/1b8dfe2ea04eee43fd362c6da0e1cef2a09cb600/controller/eks-cluster-config-handler.go#L133) every time which reenqueues the handler immediately instead of doing a …
> Remove metadata from EKS errors to stop log spamming

- go.mod
- go.sum
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>
> Update `golang.org/x/text` dependency

- README.md
Issue: https://github.com/rancher/rancher/issues/39860
> [Backport release/v1.1] Update EKS operator docs

- Dockerfile.dapper
- package/Dockerfile
Backport of https://github.com/rancher/eks-operator/pull/80
> [release/v1.1] Change to BCI and bump

- .github/workflows/apidiff.yaml
- .github/workflows/build.yaml
- .github/workflows/unit.yaml
- .github/workflows/verify.yaml
- Makefile
This PR adds a bunch of new github workflows. 
Fixes: https://github.com/rancher/eks-operator/issues/100
> Add more github workflows

- .github/workflows/unit.yaml
- Makefile
- controller/eks-cluster-config-handler.go
- controller/errors.go
- controller/nodegroup.go
- pkg/eks/create.go
- pkg/eks/create_test.go
- pkg/eks/suite_test.go
This PR adds unit tests for cluster creation and github workflows
> Unit tests for cluster creation

- controller/eks-cluster-config-handler.go
- controller/errors.go
- controller/nodegroup.go
- pkg/eks/create.go
- pkg/eks/create_test.go
- pkg/eks/delete.go
- pkg/eks/delete_test.go
> Move more aws service interactions to a separate package

- .github/workflows/nightly-publish.yaml
This change will publish the charts nightly to ttl.sh using the nightly image names.
> feat: publish nightly charts

- controller/eks-cluster-config-handler.go
The issue this PR fixes comes from the way version updates work in EKS node groups:
- "Standard" node groups, which are those created without a custom launch template, can be updated to a newer version by simply using the AWS SDK `UpdateNodegroupVersion` with the specific version the node group is expected to update to.
- Node groups created from a custom launch template (which use a custom AMI) cannot just be updated to a newer version. The only way to update these node groups is to create a new version of the launch template and point this node group to the newer version.
The eks-operator does not manage these different behaviors depending on how node groups are originally created, and hence submit a malformed request to `UpdateNodegroupVersion` in the specific case of a custom launch …
> Fix error updating node groups created with a custom launch template

- .github/workflows/e2e-latest-rancher.yaml
- .github/workflows/e2e.yaml
Report failed e2e run to slack
> Report failed e2e run to slack

- controller/eks-cluster-config-handler.go
Issue: https://github.com/rancher/eks-operator/issues/209
> Fix for node group updates

- controller/eks-cluster-config-handler.go
Issue: https://github.com/rancher/eks-operator/issues/209
Signed-off-by: Michal Jura <mjura@suse.com>
(cherry picked from commit 79bef9b198cdb62fab7f4486b770583e0d54252f)
> [2.7] Fix for node group updates

- controller/eks-cluster-config-handler.go
Issue: rancher/gke-operator#122
cc: @rancher/highlander
(cherry picked from commit 9521aa02a204e150b718b1e4664f9c0e053adbcf)
> [2.8] Check for duplicate names for NodePools

- controller/eks-cluster-config-handler.go
Issue: rancher/gke-operator#122
cc: @rancher/highlander
> Check for duplicate names for NodePools

- Makefile
- README.md
- test/e2e/deploy_operator_test.go
Fixes: https://github.com/rancher/eks-operator/issues/99
Similar to: https://github.com/rancher/aks-operator/pull/185/files
**Checklist**:
> 🌱 Update README with new instructions

- .github/workflows/build.yaml
- .github/workflows/e2e-latest-rancher.yaml
- .github/workflows/lint.yaml
- .github/workflows/scan.yaml
- .github/workflows/unit.yaml
- .github/workflows/update-rancher-charts.yaml
- .github/workflows/update-rancher-dep.yaml
- .github/workflows/verify.yaml
> Fix main branch name in workflows

- scripts/setup-kind-cluster.sh
- test/e2e/basic_cluster_test.go
- test/e2e/templates/basic-cluster.yaml
Signed-off-by: Carlos Salas <carlos.salas@suse.com>
(cherry picked from commit 545c27dc3086fe751389cf2795812f56ba430d61)
Issue #
**Checklist**:
> [v2.9] chore: add new e2e test cases

- .github/dependabot.yaml
Add dependabot rules for `release-v2.9`.
Issue #
**Checklist**:
> chore: add dependabot rules for release-v2.9

- charts/eks-operator-crd/templates/crds.yaml
- controller/eks-cluster-config-handler.go
- pkg/apis/eks.cattle.io/v1/types.go
- pkg/apis/eks.cattle.io/v1/zz_generated_deepcopy.go
- pkg/eks/create.go
- pkg/eks/create_test.go
- test/e2e/basic_cluster_test.go
- test/e2e/config/config.yaml
- test/e2e/templates/basic-cluster.yaml
cherry-pick of https://github.com/rancher/eks-operator/pull/354/commits/42018018968f26a97d08e7a8813dec3c7fc1ac0a
Issue #
**Checklist**:
> [Backport-2.9] 🌱 Add Arm support for EKS NodeGroup

- .github/workflows/apidiff.yaml
- .github/workflows/build.yaml
- .github/workflows/e2e.yaml
- .github/workflows/lint.yaml
- .github/workflows/unit.yaml
- .github/workflows/update-rancher-dep.yaml
- .github/workflows/verify.yaml
- Dockerfile.dapper
- controller/eks-cluster-config-handler.go
- go.mod
- go.sum
- test/e2e/Dockerfile.e2e
- test/e2e/config/config.go
> Bump go version to 1.21

- .github/workflows/apidiff.yaml
- .github/workflows/build.yaml
- .github/workflows/e2e.yaml
- .github/workflows/lint.yaml
- .github/workflows/unit.yaml
- .github/workflows/update-rancher-dep.yaml
- .github/workflows/verify.yaml
- Dockerfile.dapper
- controller/eks-cluster-config-handler.go
- go.mod
- test/e2e/Dockerfile.e2e
- test/e2e/config/config.go
(cherry picked from commit e165ecab5e2a87c9f78f80a13e92b22a7f84988e)
Issue #
**Checklist**:
> [v2.9] Bump go version to 1.21

- .github/workflows/apidiff.yaml
- .github/workflows/build.yaml
- .github/workflows/e2e.yaml
- .github/workflows/lint.yaml
- .github/workflows/unit.yaml
- .github/workflows/update-rancher-dep.yaml
- .github/workflows/verify.yaml
- .gitignore
- Dockerfile.dapper
- controller/eks-cluster-config-handler.go
- go.mod
- go.sum
- test/e2e/Dockerfile.e2e
- test/e2e/config/config.go
(cherry picked from commit e165ecab5e2a87c9f78f80a13e92b22a7f84988e)
Issue #
**Checklist**:
> [v2.8] Bump go version to 1.21

- .github/dependabot.yaml
We have to ignore github.com/rancher/rancher/pkg/apis because it is breaking kubernetes and wrangler modules dependency
Issue #
**Checklist**:
> Ignore github.com/rancher/rancher/pkg/apis by dependabot

- .github/dependabot.yaml
> Fix indentation for dependabot.yaml

- go.mod
- go.sum
> [v2.8] Revert go version v1.20 for v2.8

- Makefile
- go.mod
- go.sum
- scripts/setup-kind-cluster.sh
- test/e2e/config/config.yaml
- test/e2e/suite_test.go
> Fixes for e2e tests

- .github/workflows/e2e.yaml
- Makefile
> Fixes for e2e workflow

- controller/eks-cluster-config-handler.go
- test/e2e/config/config.go
(cherry picked from commit 5b6381515686f3572b3f60bef31ea8a2c4aa0151) (cherry picked from commit 55a860e49cccb777f53d0b3761f8fc4be32b7fbc)
Issue #
**Checklist**:
> [v2.7] Satisfy golangci-lint and fix tests

- Dockerfile.dapper
- package/Dockerfile
Issue: https://github.com/rancher/eks-operator/issues/407
Issue #
**Checklist**:
> security: bump operator base image to bci-micro:15.5

- controller/internal.go
> Update error verbs

- .github/workflows/release.yaml
> Final fixes to release.yaml

- charts/eks-operator/templates/deployment.yaml
Issue: https://github.com/rancher/aks-operator/issues/482
Issue #
**Checklist**:
> Update systemDefaultRegistry in helm chart

- charts/eks-operator/templates/deployment.yaml
Issue: https://github.com/rancher/aks-operator/issues/482 (cherry picked from commit 6adb4ab17c986bd056203f27deac5b18c3da30c6)
Issue #
**Checklist**:
> [v2.9] Update systemDefaultRegistry in helm chart

- charts/eks-operator/templates/deployment.yaml
Issue: https://github.com/rancher/aks-operator/issues/482 (cherry picked from commit 6adb4ab17c986bd056203f27deac5b18c3da30c6)
Issue #
**Checklist**:
> [v2.8] Update systemDefaultRegistry in helm chart

- go.mod
- go.sum
> Bump k8s.io/kubernetes to v1.29.3

- go.mod
- go.sum
> [v2.8] Bump k8s.io/kubernetes to v1.28.8

- go.mod
- go.sum
> [v2.7] Bump k8s.io/kubernetes to v1.27.13

- Dockerfile.dapper
> Bump go version to v1.21.10

- Dockerfile.dapper
(cherry picked from commit 7018d38668186f1713cf62a87415adba71888a78)
Issue #
**Checklist**:
> [v2.9] Bump go version to v1.21.10

- go.mod
- go.sum
> Downgrade controller-runtime dependency to v1.15.3

- controller/eks-cluster-config-handler.go
After AWS SKD migration error handling changed, so we can remove unneeded function removeErrorMetadata.
Issue: https://github.com/rancher/eks-operator/issues/541 (cherry picked from commit cee78abb5d26536730dcf502a884ff5aede4649b)
Issue #
**Checklist**:
> [v2.9] Refactoring recordError func after AWS SDK migration

- .github/workflows/update-rancher-charts.yaml
- .github/workflows/update-rancher-dep.yaml
Due to a missing curly bracket, the workflow for updating rancher charts is [invalid](https://github.com/rancher/eks-operator/actions/runs/9413480674/workflow). Also updated Go version used for running go commands from the rancher/rancher side.
**Checklist**:
> [v2.9] fix: Fix workflows used to update rancher/charts and rancher/rancher

- scripts/setup-kind-cluster.sh
- test/e2e/templates/basic-cluster.yaml
Issue: https://github.com/rancher/eks-operator/issues/622
Issue #
**Checklist**:
> [v2.9] Drop support for Kubernetes v1.26

- .drone.yml
- .github/workflows/release.yaml
- .goreleaser.yaml
Up until recently, creating a new GitHub release (and associated artifacts) when a new tag was created, was being done using Drone CI. Now that Drone CI has been deprecated, there is a GitHub Actions workflow that is responsible for doing this. In fact, most of the work is delegated to goreleaser which is being invoked as part of that workflow.
Issue #654 
**Checklist**:
> ci: Add goreleaser config and update release workflow

- controller/eks-cluster-config-handler.go
Downgrading Kubernetes cluster is not supported.
Issue: https://github.com/rancher/eks-operator/issues/668
Issue #
**Checklist**:
> Prevent from downgrading Kubernetes versions

- controller/eks-cluster-config-handler.go
(cherry picked from commit 200e2683ad5cb3e8b90b15fd38ac5ec332217627)
Issue #
**Checklist**:
> [v2.9] Prevent from downgrading Kubernetes versions

- controller/eks-cluster-config-handler.go
Check for Kubernetes update only if config and upstream version are not nil.
Issue: https://github.com/rancher/eks-operator/issues/686 (cherry picked from commit 61bd24f2d3096cdea65458a5dbb0c84428045cec)
Issue #
**Checklist**:
> Additional check for Kubernetes update

- controller/eks-cluster-config-handler.go
Check for Kubernetes update only if config and upstream version are not nil.
Issue: https://github.com/rancher/eks-operator/issues/686 (cherry picked from commit 61bd24f2d3096cdea65458a5dbb0c84428045cec)
Issue #
**Checklist**:
> [v2.9] Additional check for Kubernetes update

- charts/eks-operator/templates/deployment.yaml
1. Restrict container from acquiring additional privileges (`securityContext.allowPrivilegeEscalation`)
2. Mount container's root filesystem as read only (`securityContext.readOnlyRootFilesystem`)
3. Ensure that container won't be started as privileged container (`securityContext.privileged`)
Issue: https://github.com/rancher/aks-operator/issues/591 (cherry picked from commit cbc7c130501a7611a6480b08fd9ae9c9517de150)
Issue #
**Checklist**:
> [v2.9] Improve securityContext for operator Deployment

- charts/eks-operator/templates/deployment.yaml
1. Restrict container from acquiring additional privileges (`securityContext.allowPrivilegeEscalation`)
2. Mount container's root filesystem as read only (`securityContext.readOnlyRootFilesystem`)
3. Ensure that container won't be started as privileged container (`securityContext.privileged`)
Issue: https://github.com/rancher/aks-operator/issues/591
Issue #
**Checklist**:
> Improve securityContext for operator Deployment

- controller/eks-cluster-config-handler.go
- controller/external.go
- pkg/eks/get.go
- pkg/eks/get_test.go
Issue: https://github.com/rancher/eks-operator/issues/106 (cherry picked from commit c58527cfdbf123d18d077b7d0ee600935af33ace)
Issue #
**Checklist**:
> [v2.9] Set information about CSI EBS driver

- controller/eks-cluster-config-handler.go
- controller/external.go
- pkg/eks/get.go
- pkg/eks/get_test.go
Issue: https://github.com/rancher/eks-operator/issues/106
Issue #
**Checklist**:
> Set information about CSI EBS driver

- controller/eks-cluster-config-handler.go
- controller/external.go
> Fix Rancher integration for BuildUpstreamClusterState

- controller/eks-cluster-config-handler.go
- controller/external.go
(cherry picked from commit df4ef25d388e74026caac85592270a6fe25c3611)
Issue #
**Checklist**:
> [v2.9] Fix Rancher integration for BuildUpstreamClusterState

- .github/workflows/release.yaml
- go.mod
- package/Dockerfile
- test/e2e/Dockerfile.e2e
(cherry picked from commit 42f6676e1fdfefbe2447a851bc5a28d49240bfb0)
Issue #
**Checklist**:
> [v2.8] Enforce latest go version and bump to bci image to 15.6

- controller/eks-cluster-config-handler.go
> Fixing non-constant format string in call

- controller/eks-cluster-config-handler.go
(cherry picked from commit 0ec28e48ed8823444c076da896f550c4665e32c8)
Issue #
**Checklist**:
> [v2.9] Fixing non-constant format string in call

- controller/eks-cluster-config-handler.go
(cherry picked from commit 0ec28e48ed8823444c076da896f550c4665e32c8)
Issue #
**Checklist**:
> [v2.8] Fixing non-constant format string in call

- controller/eks-cluster-config-handler.go
- controller/eks-cluster-config-handler_test.go
- controller/nodegroup.go
- pkg/eks/create.go
- pkg/eks/delete.go
- pkg/eks/update.go
/kind enhancement
1. Use [cluster-name (id: cluster-id)] instead of either [cluster-name] or [cluster-id]
2. Log more information
Issue #
**Checklist**:
> Enhance logs

- go.mod
> Bump Kubernetes to v1.29.7

- go.mod
(cherry picked from commit 34c2de57893265f71a4d5857753bdef7ffd98361)
Issue #
**Checklist**:
> [v2.9] Bump Kubernetes to v1.29.7

- controller/eks-cluster-config-handler.go
(cherry picked from commit d38ca754e3738cf330855c6fdc811ac4ec54e247)
The error log in the bug report indicates that there is a conflict when updating the status:
```
the object has been modified; please apply your changes to the latest version and try again
```
Issue #596 
**Checklist**:
> [v2.9] Retry operation on conflict

- controller/eks-cluster-config-handler.go
Issue: https://github.com/rancher/eks-operator/issues/752
Issue #
**Checklist**:
> Change order of applying changes to EKS

- controller/eks-cluster-config-handler.go
Issue: https://github.com/rancher/eks-operator/issues/752
Issue #
**Checklist**:
> [v2.9] Change order of applying changes to EKS

- controller/eks-cluster-config-handler.go
- controller/eks-cluster-config-handler_test.go
> [v2.9] update version skew policy 

- controller/eks-cluster-config-handler.go
Reverts rancher/eks-operator#848
> Revert "[v2.9] Retry operation on conflict"

- .github/workflows/release.yaml
- .github/workflows/scan.yaml
- package/Dockerfile
Bump base image version to 15.6. Also updated release and scan workflows to use the same version of Go, which is the one specified in go.mod.
**Checklist**:
> [v2.7] Bump image version

- controller/eks-cluster-config-handler.go
(cherry picked from commit https://github.com/rancher/eks-operator/pull/876/commits/d8cbcb553758bd9e4d81b96e97797041cb5cb0d2)
Reverts https://github.com/rancher/eks-operator/pull/835
> Revert "[main] fix: Retry operation on conflict"

- .github/workflows/nightly-publish.yaml
Removed obsolete parameter from referenced workflow.
**Checklist**:
> ci: Remove obsolete parameter

- controller/external.go
- pkg/eks/create.go
- pkg/eks/create_test.go
Issue: https://github.com/rancher/eks-operator/issues/568
Issue #
**Checklist**:
> Bump AMI Amazon Linux 2023 with Nvidia support

- controller/external.go
- pkg/eks/create.go
- pkg/eks/create_test.go
Issue: https://github.com/rancher/eks-operator/issues/568 (cherry picked from commit cb550c15d49e6bcb44259675714bf9f827e6e865)
Issue #
**Checklist**:
> [v2.10] Bump AMI Amazon Linux 2023 with Nvidia support

- pkg/eks/create.go
- pkg/eks/create_test.go
Signed-off-by: Danil-Grigorev <danil.grigorev@suse.com>
(cherry picked from commit 8c4bed53b9dbd48361727e4da09335424aa0f127)
Issue #
**Checklist**:
> [v2.9] Prevent panic on no launch template ID

- pkg/eks/create.go
- pkg/eks/create_test.go
Signed-off-by: Danil-Grigorev <danil.grigorev@suse.com>
(cherry picked from commit 8c4bed53b9dbd48361727e4da09335424aa0f127)
Issue #
**Checklist**:
> [v2.10] Prevent panic on no launch template ID

- Makefile
- package/Dockerfile
Backport of https://github.com/rancher/eks-operator/pull/1068
Issue #1067 
**Checklist**:
> [v2.8] VEX related improvements in the build process

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- Makefile
- package/Dockerfile
- pkg/version/version.go
(cherry picked from commit e86cf8a5b84988915419bb080e11d36af1209426)
This PR changes the build process to be self-contained: it no longer requires the application to be build outside the container and relying on go version in the CI runner, instead the build is done in a build layer.
It also updates the release workflow to additionally push images to Prime Registry.
Finally it uses [cross-compilation helpers](https://github.com/tonistiigi/xx?tab=readme-ov-file#go--cgo) to invoke the Go compiler with the correct env vars for the target platform.
Issue #1089
**Checklist**:
> [2.10] ci: Make release SLSA compliant

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- Makefile
- package/Dockerfile
- pkg/version/version.go
(cherry picked from commit e86cf8a5b84988915419bb080e11d36af1209426)
This PR changes the build process to be self-contained: it no longer requires the application to be build outside the container and relying on go version in the CI runner, instead the build is done in a build layer.
It also updates the release workflow to additionally push images to Prime Registry.
Finally it uses [cross-compilation helpers](https://github.com/tonistiigi/xx?tab=readme-ov-file#go--cgo) to invoke the Go compiler with the correct env vars for the target platform.
Issue #1089
**Checklist**:
> [2.9] ci: Make release SLSA compliant

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- Makefile
- package/Dockerfile
- pkg/version/version.go
(cherry picked from commit e86cf8a5b84988915419bb080e11d36af1209426)
This PR changes the build process to be self-contained: it no longer requires the application to be build outside the container and relying on go version in the CI runner, instead the build is done in a build layer.
It also updates the release workflow to additionally push images to Prime Registry.
Finally it uses [cross-compilation helpers](https://github.com/tonistiigi/xx?tab=readme-ov-file#go--cgo) to invoke the Go compiler with the correct env vars for the target platform.
Issue #1089 
**Checklist**:
> [2.8] ci: Make release SLSA compliant

- .github/workflows/e2e-branch.yaml
- .github/workflows/e2e-workflow.yaml
Push test images to ghcr.io instead of ttl.sh.
Issue #
**Checklist**:
> ci: Push test images to ghcr.io instead of ttl.sh

- .github/workflows/nightly-publish.yaml
Push nightly charts and images to ghcr.io
**Checklist**:
> ci: Push nightly charts and images to ghcr.io

- charts/eks-operator/Chart.yaml
- charts/eks-operator/values.yaml
bumped chart version to v1.11.0-rc.3
Issue #
**Checklist**:
> [v2.11] bumped chart version to v1.11.0-rc.3

- .github/workflows/release.yaml
fix dispatch action workflow
Issue #
**Checklist**:
> [v2.11] fix dispatch github action

- controller/eks-cluster-config-handler.go
- controller/eks-cluster-config-handler_test.go
- https://github.com/rancher/eks-operator/issues/1208
> [backport][v2.10] handle conflict errors while updating eksClusterConfig

- charts/eks-operator-crd/templates/crds.yaml
- controller/eks-cluster-config-handler.go
- controller/eks-cluster-config-handler_test.go
- pkg/apis/eks.cattle.io/v1/types.go
- pkg/apis/eks.cattle.io/v1/zz_generated_deepcopy.go
- pkg/eks/get.go
- pkg/eks/get_test.go
- pkg/eks/services/eks.go
- pkg/eks/services/mock_services/eks_mock.go
- https://github.com/rancher/eks-operator/issues/1207
> [release-v2.10] check upstream cluster updates in the cluster as well while updating

- .github/workflows/release.yaml
added app token to fix rancher go get dispatch
Issue #
**Checklist**:
> [release-v2.11] fix rancher go get dispatch

- .github/workflows/release.yaml
> [release-v2.11] fix linting in release github action

- .github/workflows/release.yaml
> fix go get workflow permission

- .github/workflows/release.yaml
fix dispatch workflows
Issue #
**Checklist**:
> [release-v2.11] fix app token generation and enable dispatch chart

- .github/workflows/release.yaml
sync the release workflow with release-v2.11 branch.
- added the charts branch creation step
- added go get dispatch workflow
Issue #
**Checklist**:
> [main] sync release workflow with release-v2.11

- .github/workflows/release.yaml
fixed the branches for go get dispatch workflow and commented out dispatch chart workflow.
Issue #
**Checklist**:
> [release-v2.11] fix go get dispatch branches

- .github/workflows/release.yaml
> [release-v2.9] sync release workflow with release-v2.11

- .github/workflows/release.yaml
- charts/eks-operator/Chart.yaml
Add support for auto chart bump in release GHA
Issue [#48796](https://github.com/rancher/rancher/issues/48796)
**Checklist**:
> bumped the chart version to support v1.12 

- .github/workflows/e2e-workflow.yaml
added 2.12 e2e tests in workflow
Issue #
**Checklist**:
> added 2.12 e2e tests in workflow

- .github/dependabot.yaml
added step to ignore lasso for v2.11
Issue #
**Checklist**:
> added step to ignore lasso for v2.11

- .github/workflows/release.yaml
corrected workflow to extract the correct branch name
Issue #
**Checklist**:
> corrected workflow to extract the correct branch name
